modLoader = "javafml"
loaderVersion = "*"
license = "GNU GPL 3.0"

[[mods]]
modId = "stellarity"
version = "0.3.2"
displayName = "Stellarity Enlightened"
authors = "Authors"
description = "Example description"
logoFile = "assets/stellarity/icon.png"
logoBlur = false

[[dependencies."stellarity"]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[1.20,1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies."stellarity"]]
modId = "architectury"
mandatory = true
type = "required"
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "stellarity-common.mixins.json"

[[mixins]]
config = "stellarity-neoforge.mixins.json"